[project]
name = "popbot"
version = "0.1.0"
description = "bot discord"
authors = ["chahyn <chahynfg@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "pytz>=2025.2",
    "requests>=2.32.4",
]
